name: "Test"
on:
  - "push"
jobs:
  test:
    name: "Color Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: deno run -A test.ts
